config/routes.rb
CoasterProject::Application.routes.draw do
  get '/log_in' => 'sessions#new', as: 'log_in'
  get '/sign_up' => 'users#new', as: 'sign_up'
  get '/log_out' => 'sessions#destroy', as: 'log_out'
  put '/coasters/:id/user_list' => 'coasters#user_list', as: 'user_list'
  root :to => 'welcome#index'
  resources :coasters, :parks, :users, :sessions

end

app/models/Coaster.rb
# == Schema Information
#
# Table name: coasters
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  park_id    :integer
#  material       :string(255)
#  height     :integer
#  length     :integer
#  speed      :integer
#  inversions :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Coaster < ActiveRecord::Base
  # makes all user attributes accessible
  attr_accessible :name, :park_id, :material, :height, :length, :speed, :inversions
  # requires existence of coaster attributes to input
  validates :name, :park_id, presence: true
  # prevents negative and non-numerical values for coaster specs
  validates :height, :length, :speed, :inversions, :allow_nil => true, :numericality => { :greater_than_or_equal_to => 0 }
  # defines relationship between coasters and users
  has_and_belongs_to_many :users
  # defines relationship between coasters and parks
  belongs_to :parks
end

app/controllers/coasters_controller.rb
class CoastersController < ApplicationController
  def index
    # all coasters matching search
    # may want to use wildcards and/or titleize to allow for inexact searches
    @coasters = Coaster.where(name: params[:query])
    # leave user here in case we allow coasters to be added to user list from search results
    @user = current_user
    # finds all parks of coasters returned by query
    park_ids = @coasters.pluck(:park_id).uniq
    @coasters_parks = Park.find(park_ids)
    # passes queried-for coasters' parks into API for Google Maps
    @json = @coasters_parks.to_gmaps4rails
  end

  def show
    # calls user to allow for adding coasters to user list
    @user = current_user
    # calls coaster with id and that coaster's park
    @coaster = Coaster.find(params[:id])
    @park = Park.find(@coaster.park_id)
    # passes coaster's parks into API for Google Maps
    @json = @park.to_gmaps4rails
  end

  def new
    # will not allow person to add coasters unless logged in
    @user = current_user
    if @user.nil?
      redirect_to root_url
    end
    @coaster = Coaster.new
  end

  def create
    @coaster = Coaster.new(params[:coaster])
    # will only save and redirect if validation is met
    # otherwise, will remain in '/coasters/new'
    if @coaster.save
      redirect_to root_url, notice: "Added coaster to database!"
    else
      render "new"
    end
  end

  def edit
    # will not allow person to edit coasters unless logged in
    @user = current_user
    if @user.nil?
      redirect_to root_url
    end
    @coaster = Coaster.find(params[:id])
  end

  def update
    @coaster = Coaster.find(params[:id])
    @coaster.material = params[:coaster][:material]
    @coaster.height = params[:coaster][:height]
    @coaster.length = params[:coaster][:length]
    @coaster.speed = params[:coaster][:speed]
    @coaster.inversions = params[:coaster][:inversions]
    if @coaster.save
      redirect_to "/coasters/#{params[:id]}"
    else
      @id = params[:id]
      render action: "edit"
    end
  end

  def user_list
    user = current_user
    id = params[:id].to_i
    coaster_array = user.coasters.pluck(:id)
    if params[:ridden].nil? == false
      if coaster_array.include?(id) == false
        user.coasters << Coaster.find(id)
      end
    else
      id = params[:id].to_i
      if coaster_array.include?(id)
        user.coasters.delete(Coaster.find(id))
      end
    end
    redirect_to "/users/#{user.id}"
  end
end

app/views/coasters/_errors.html.erb
<% if @coaster.errors.any? %>
  <div class="text-error">
    <h2>Form is invalid</h2>
    <ul>
      <% @coaster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/coasters/_links.html.erb
<br/>
<% if current_user %>
  <%= link_to "Add a new park", new_park_path %><br/>
  <%= link_to "Add a new coaster", new_coaster_path %>
<% else %>
  Log in or sign up to add new parks and coasters.
<% end %>

app/views/coasters/_results.html.erb
<% if @coasters.present? %>
  <h3>Search results</h3>
  <ul>
  <% @coasters.each do |coaster| %>
  <! provides links for each roller coaster called and that roller coaster's park >
    <li class="results"><%= link_to coaster.name, coaster %>
      (Park: <%= link_to Park.find(coaster.park_id).name, Park.find(coaster.park_id) %>)</li>
  <% end %>
  </ul>
<% end %>

app/views/coasters/edit.html.erb
<h1>Edit coaster</h1>

<! form to edit a coaster >
<%= form_for @coaster do |f| %>

  <! if the form is filled out incorrectly, this will return an error message, and details of the issues >
  <%= render 'errors' %>

  <!-- only name and park_id are necessary
  users cannot edit these values after coaster is created -->
  <%= f.label :name %>:
  <%= @coaster.name %><br/>
  <%= f.label :park_id %>:
  <%= Park.find(@coaster.park_id).name %><br/>
  <%= f.label :material %>
  <%= f.text_field :material %><br/>
  <%= f.label :height %> in feet
  <%= f.number_field :height %><br/>
  <%= f.label :length %> in feet
  <%= f.number_field :length %><br/>
  <%= f.label :speed %> in mph
  <%= f.number_field :speed %><br/>
  <%= f.label :inversions %>
  <%= f.number_field :inversions %><br/>

  <%= f.submit %>

<% end %>

<%= render 'links' %>

app/views/coasters/index.html.erb
<div class="left">
<h1>Search for coasters</h1>

<! query form to search for coasters - may want to use wildcards and/or titleize to allow for inexact searches >
<%= form_tag('/coasters', method: 'get') do %>
  <%= text_field_tag(:query, nil ,:placeholder => 'Search for a coaster') %>
  <%= submit_tag 'Search' %>
<% end %>

<! Returns error message if search returns no results. >
<% if @coasters.empty? && params[:query] %>
  <h3>No results returned.</h3>
<% end %>

<!-- turn results into a form to add or remove coasters from user's coaster list - can we do more than one at a time with checkboxes? -->
<%= render 'results' %>

<%= render 'links' %><br/><br/>

<h4>Due to limited functionality, we're currently providing a list of all coasters in our database.</h4>
<% Coaster.all.each do |coaster| %>
  <li class="results"><%= link_to coaster.name, coaster %>
    (Park: <%= link_to Park.find(coaster.park_id).name, Park.find(coaster.park_id) %>)</li>
<% end %>
</div>

<!-- API for Google Maps - set up to show the parks of the queried-for coasters
will only show up if search is run and returns coasters -->
<% if @coasters && params[:query] %>
  <div class="right">Location of parks for coasters returned by your search<%= gmaps4rails(@json) %></div>
<% else %>
  <div class="right"><img src="http://www.placesaroundflorida.com/images/Tampa/Montu-Busch-Gardens.jpg"/><br/><br/><br/>
    <img src="http://etherealwellness.files.wordpress.com/2012/10/emotional-roller-coaster.jpg"/>
    </div>
<% end %>

app/views/coasters/new.html.erb
<div><h1>Add a coaster to the database</h1></div>

<! form to add a new coaster >
<div class="left">
<%= form_for @coaster do |f| %>

  <! if the form is filled out incorrectly, this will return an error message, and details of the issues >
  <%= render 'errors' %>

  <! only name and park_id are necessary to create coaster - need for park_id means that park must be created before coaster >
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :park_id %>
  <%= f.collection_select :park_id, Park.all, :id, :name, prompt: true %><br/>
  <%= f.label :material %>
  <%= f.text_field :material %><br/>
  <%= f.label :height %>
  <%= f.number_field :height %><br/>
  <%= f.label :length %>
  <%= f.number_field :length %><br/>
  <%= f.label :speed %>
  <%= f.number_field :speed %><br/>
  <%= f.label :inversions %>
  <%= f.number_field :inversions %><br/>

  <%= f.submit %>

<% end %>

<%= render 'links' %>
</div>

<div class="right"><img src="http://www.joyrides.com/cedar_point/photos/raptor6.jpg"/></div>

app/views/coasters/show.html.erb
<! shows a coaster and that coaster's park >
<div class="left">
<h1>Coaster: <%= @coaster.name %></h1>
<h3>Park: <%= link_to @park.name, park_path %></h3>

<!-- if a user is logged in, creates check box to be checked if user has ridden coaster
box can be unchecked to remove coaster from user's list, as well -->
<% if @user %>
  <%= form_tag(user_list_path, method: 'put') do %>
    <%= label_tag "Have you ridden this coaster?" %>
    <%= check_box_tag "ridden", @user.coasters.include?(@coaster), @user.coasters.include?(@coaster) %>
    <%= submit_tag 'Update Coaster List' %>
  <% end %>
<% end %>

<! lists coaster's attributes >
<ul>
  <li>Type: <%= @coaster.material %></li>
  <li>Height: <%= @coaster.height %> ft</li>
  <li>Length: <%= @coaster.length %> ft</li>
  <li>Speed: <%= @coaster.speed %> mph</li>
  <li>Inversions: <%= @coaster.inversions %></li>
</ul>

<br/>
<% if current_user %>
  <%= link_to "Edit this coaster", edit_coaster_path %>
<% else %>
  Log in or sign up to edit this coaster.
<% end %>

<%= render 'links' %>
</div>

<! API for Google Maps - set up to show the coaster's park >
<div class="right">Location of this coaster's park<%= gmaps4rails(@json) %></div>