config/routes.rb
CoasterProject::Application.routes.draw do
  get '/log_in' => 'sessions#new', as: 'log_in'
  get '/sign_up' => 'users#new', as: 'sign_up'
  get '/log_out' => 'sessions#destroy', as: 'log_out'
  put '/coasters/:id/user_list' => 'coasters#user_list', as: 'user_list'
  root :to => 'welcome#index'
  resources :coasters, :parks, :users, :sessions

end

app/models/User.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  user_name  :string(255)
#  email      :string(255)
#  password   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base

  # This gives us setter/getter methods
  # This might not be in the database
  attr_accessor :password
  before_save :encrypt_password

  # # This checks that the password_confirmation == password
  # # Automatically gives us the password_confirmation setter
  validates :password, confirmation: true
  validates :password, presence: true, on: :create
  # # requires password_confirmation presence
  validates :password_confirmation, presence: true

  # defines relationship between users and coasters
  has_and_belongs_to_many :coasters
  # makes all user attributes accessible
  attr_accessible :user_name, :email, :password, :password_confirmation
  # requires existence of all user attributes
  validates :user_name, :email, presence: true
  # defines maximum length for all user attributes
  validates :user_name, :email, :password, length: { maximum: 40 }
  # requires unique user name and email address
  validates :user_name, :email, uniqueness: true
  # requires password to be at least 8 letters
  validates :password, length: { minimum: 8 }



  def encrypt_password
    if password.present?
      # This generates a random string that helps me encrypt the password
      self.password_salt = BCrypt::Engine.generate_salt

      # This encrypts the password, using the salt we just created
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(user_name, password)
    # This will auth a user
    user = User.find_by_user_name(user_name)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # if a session is in progress, redirects to the user show page
    # otherwise, displays index page (almost blank at present)
    @user = current_user
    if @user
      redirect_to "/users/#{@user.id}"
    else
      redirect_to root_url
    end
  end

  def show
    # takes logged in user
    @user = current_user
    # finds all parks at which that user has ridden a coaster
    park_ids = @user.coasters.pluck(:park_id).uniq
    @user_parks = Park.find(park_ids)
    # passes user's parks into API for Google Maps
    @json = @user_parks.to_gmaps4rails
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    # will only save and redirect if validation is met - otherwise, will remain in sign_up
    if @user.save
      # is there any way to log in a newly signed up user automatically?
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Signed up!"
    else
      render "new"
    end
    # @user = User.new
    # @user.name = params[:name]
    # @user.user_name = params[:user_name]
    # @user.email = params[:email]
    # @user.password = params[:password]
    # if @user.save
    #   redirect_to "/users/#{params[:id]}"
    # else
    #   render action: "new"
    # end
  end

  def edit
    @user = User.find(params[:id])
    @id = params[:id]
  end

  def update
    @user = User.find(params[:id])
    @user.user_name = params[:user][:user_name]
    @user.email = params[:user][:email]
    # need to require password confirmation to update
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      redirect_to "/users/#{params[:id]}"
    else
      @id = params[:id]
      render action: "edit"
    end
  end

  def destroy
    # removes user from database
    User.find(params[:id]).destroy
    # effectively logs out, so session is not calling a non-existent user id
    session[:user_id] = nil
    redirect_to root_url, notice: "Profile deleted.  Sorry to see you go."
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <! If the form is filled out incorrectly, this will return an error message, and details of the issues >
  <% if @user.errors.any? %>
    <div class="text-error">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :user_name %>
  <%= f.text_field :user_name %><br/>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>
  <%= f.label :password %> (min. 8 characters)<br/>
  <%= f.password_field :password %><br/>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br/>

  <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<! form to edit a current user>
<%= render 'form' %>

<! form to delete user profile >
<%= form_tag("/users/#{@id}", method: 'delete') do %>
  <div class="btn btn-danger"><%= submit_tag 'Delete Profile' %></div>
<% end %>

app/views/users/index.html.erb
<h1>Hello, <%= @user.user_name %>!</h1>

<h3>I don't think you'll ever see this.</h3>

app/views/users/new.html.erb
<div class="left">
  <h1>Sign up</h1>

  <! Form to add a new user >
  <%= render 'form' %>
</div>

<div class="right"><img src="http://farm2.staticflickr.com/1049/4723156854_7eaf42b467_z.jpg"></div>

app/views/users/show.html.erb
<div class="left">
<h1>Hello, <%= @user.user_name %>!</h1>

<h3>Here are the coasters you've ridden.</h3>
<% if @user_parks.nil? %>
  <p>Please feel free to search for coasters to start your list.</p>
<% end %>

<!-- list of all parks in which user has ridden a roller coaster
each park has a list of coasters the user has ridden at that park
each list item links to page for that park/coaster -->
<ul>
  <% @user_parks.each do |park| %>
  <li class="results"><%= link_to park.name, park %></li>
  <ul>
    <% @user.coasters.where(park_id: park.id).each do |coaster| %>
      <li class="results"><%= link_to coaster.name, coaster %></li>
    <% end %>
  </ul>
  <% end %>
</ul>

<! link to edit profile page >
<%= link_to "Update your profile", edit_user_path %><br/><br/>
</div>

<! API for Google Maps - set up to show the user's parks >
<div class="right">Location of parks you've visited<%= gmaps4rails(@json) %></div>